### PR TITLE
Update PyCon.net homepage for PyCon 2024

### PR DESCRIPTION
**Pull request by ntoll**
First pass. 

* A real PyScript terminal.
* Typing code.
* Updated copy.

### CODE REVIEW

**Comment by ntoll** [comment]
@WebReflection There is a problem with this branch.

When the "typed in" text is of a width > 50% of the terminal, Xterm.js (or something in the JS side of things) just spews out a bunch of the most recent characters. This means it doesn't work well on mobile! 

Here's a video to show what I mean:

term_fail

Here's what the end result *should* look like:

```
MicroPython v1.23.0-preview.355.gbe1ecb54e on 2024-05-07; JS with Emscripten
Type "help()" for more information.
>>> print("Hello, from PyScript!")
Hello, from PyScript!
>>> # Your turn...
>>> 
```

Any idea how to fix this..?

**Comment by WebReflection** [comment]
this is not a real-world issue, isn't it? it's you messing around with the UI mode in your browser but even with regular terminals if you resize the window chars might be repositioned awkwardly and I don't want to dig internals of Readline, AutoFit and other plugins we have, if possible, unless you have real issues with real phones, which is not the case for what I could test. In short, it's not our code and the program runs without issue, how much effort should I spend investigating reactivity with concrete issues on mobile?

**Comment by ntoll** [comment]
Hey hey. This is definitely a real world issue since we want folks to see PyScript working on their mobile phones, and it doesn't work properly at the moment. The repeated characters simply shouldn't be there and I'm not sure what's going on because Xterm "should" (note the air quotes) just work :tm:. Perhaps a quick Zoom call will help..?

**Comment by WebReflection** [comment]
> Hey hey. This is definitely a real world issue since we want folks to see PyScript working on their mobile phones

My point was: it's you using a Desktop browser and changing at runtime its screen capabilities ... if you connect with a phone in that site you will not see the issue, as far as I can tell. You clicking / toggling Desktop / iOS on your Desktop browser *might* be the issue. We don't do anything special with resize, we have an AutoFit plugin and Xterm and apparently it doesn't just work so my wonder is how much time should we spend on this as we don't do any special chars parsing at the `stdio` level for screen size, we don't even have a listener for the resize event in our code.

I hope this better explains my previous comment.

**Comment by WebReflection** [comment]
@ntoll I've amended or removed my previous comments and I feel like I should apology I focused too much on the video and the resize behind instead of checking what is it that wasn't working as expected. We found the culprit so you are not blocked anymore but again, sorry for the rushed reply, I've been around terminals and MicroPython too much lately 😅

**Comment by ntoll** [comment]
@WebReflection absolutely no problem at all. The important thing is we carefully and conscientiously worked the problem, fixed it and refined the solution. When I have the thing working to my satisfaction, I'll paste a link to the "test" version on PSDC so folks can see it in action and test in on devices. :+1:

**Comment by ntoll** [comment]
OK. It's ready.

Look at it in action here (thank you PSDC): https://pyscript.com/@ntoll/pyscript-net/latest

@WebReflection I have sinned - I used userAgent to sort of Firefox mobile. :-D

**Comment by ntoll** [comment]
@WebReflection I fixed it. ;-)

**Review by WebReflection — APPROVED** [review]

**Review by mchilvers — APPROVED** [review]

**Pull request merged**
