### PR TITLE
Add a privacy policy for the newsletter.

### PR DESCRIPTION
**Pull request by ntoll**
Does exactly what it says on the tin.

### CODE REVIEW

**Comment by ntoll** [comment]
Looks like this:

Screenshot 2024-08-14 at 18-17-50 PyScript's privacy policy

**Review by JoshuaLowe1002 — APPROVED** [review]

**Review by fpliger — COMMENTED** [review]
I think we shouldn't mention Anaconda here (or at least as the author of this privacy agreement). I think it's fair to mention this is based off Anaconda's privacy/data collection terms but it's owned and managed by the PyScript OSS maintainers, not Anaconda

**Comment by ntoll** [comment]
@fpliger the actual text was what was approved by Anaconda' legal department.

**Comment by fpliger** [comment]
> @fpliger the actual text was what was approved by Anaconda' legal department.

I don't think that really matters (I mean... i does in the sense that we have consulted experts in the matter and are basing our working on their guidance) but, ultimately, this policy is owned by the PyScript Maintainers team and Anaconda doesn't own  it....

**Comment by dashagurova** [comment]
I agree with Fabio, Anaconda legal team contributed their time and expertise to review the privacy policy we wrote. I also think that Anaconda legal team would prefer it that way (to not be mentioned)

**Pull request merged**
